/*
 * Copyright (c) 2024-2026. Freaklog contributors.
 * This file is part of Freaklog.
 *
 * Freaklog is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 */

package foo.pilz.freaklog.data.room

import androidx.room.Room
import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Room database migration tests.
 *
 * Every `AutoMigration` registered in [AppDatabase] should be exercised here:
 *
 *   1. We create a database at the source schema version.
 *   2. We close it and re-open it at the target version, asking Room to apply
 *      every registered migration.
 *   3. We then validate the database is openable through the normal Room
 *      builder (which runs `validateMigration` on every entity).
 *
 * If a future contributor adds an `AutoMigration` they are responsible for
 * adding the corresponding `from -> to` pair in [migrationPairs] below.
 *
 * Note: schema version 13 was skipped (the migration jumps 12 -> 14), so any
 * pair containing 13 is intentionally absent.
 */
@RunWith(AndroidJUnit4::class)
class AppDatabaseMigrationTest {

    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
    )

    @Test
    fun migrate_individual_pairs_succeeds_for_every_registered_auto_migration() {
        for ((from, to) in migrationPairs) {
            // Create the DB at the older schema version.
            helper.createDatabase(TEST_DB, from).apply { close() }

            // Re-open it at the target version. `validateDroppedTables = true`
            // catches accidental drops in autogenerated SQL.
            helper.runMigrationsAndValidate(
                TEST_DB,
                to,
                /* validateDroppedTables = */ true,
            ).close()
        }
    }

    @Test
    fun migrate_all_the_way_from_v1_to_latest_succeeds() {
        helper.createDatabase(TEST_DB, 1).apply { close() }
        helper.runMigrationsAndValidate(
            TEST_DB,
            AppDatabase.LATEST_SCHEMA_VERSION,
            /* validateDroppedTables = */ true,
        ).close()
    }

    @Test
    fun migrate_from_oldest_yields_same_schema_as_fresh_database() {
        // Migrate from v1.
        helper.createDatabase(TEST_DB, 1).apply { close() }
        helper.runMigrationsAndValidate(
            TEST_DB,
            AppDatabase.LATEST_SCHEMA_VERSION,
            /* validateDroppedTables = */ true,
        ).close()

        // Now actually open the migrated database via Room. Room will run its
        // own `validateMigration` against the entity metadata; if anything is
        // mis-aligned (column type, index, FK) this throws.
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val db = Room.databaseBuilder(context, AppDatabase::class.java, TEST_DB)
            .openHelperFactory(FrameworkSQLiteOpenHelperFactory())
            .build()
        try {
            // Touch a table to force the database to be opened/validated.
            val cursor = db.openHelper.writableDatabase.query("SELECT 1")
            assertNotNull(cursor)
            cursor.close()
            // Sanity-check the user_version pragma to verify we landed on the
            // expected schema version.
            val versionCursor = db.openHelper.writableDatabase.query("PRAGMA user_version")
            versionCursor.use {
                check(it.moveToFirst())
                assertEquals(AppDatabase.LATEST_SCHEMA_VERSION, it.getInt(0))
            }
        } finally {
            db.close()
        }
    }

    companion object {
        private const val TEST_DB = "migration-test.db"

        /**
         * Every consecutive pair of schema versions for which an
         * `AutoMigration` is registered. Keep in sync with the
         * `autoMigrations = [...]` block in [AppDatabase].
         *
         * Schema 13 was skipped, hence the (12, 14) pair.
         */
        private val migrationPairs: List<Pair<Int, Int>> = listOf(
            1 to 2,
            2 to 3,
            3 to 4,
            4 to 5,
            5 to 6,
            6 to 7,
            7 to 8,
            8 to 9,
            9 to 10,
            10 to 11,
            11 to 12,
            12 to 14,
            14 to 15,
            15 to 16,
            16 to 17,
            17 to 18,
        )
    }
}
