---
name: Build on ubuntu
on:
  push:
  pull_request:
env:
  main_project_module: 'app'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Load JDK
      run: nix develop .

    - name: build app
      run: nix run github:tadfisher/gradle2nix/v2 -- assembleRelease

    - uses: actions/upload-artifact@v4
      with:
        name: "freaklog-unsigned.apk"
        path: app/build/outputs/apk/release/app-release-unsigned.apk
        if-no-files-found: error
  sign:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download unsigned APK
        if: >
          github.event_name == 'push'
        uses: actions/download-artifact@v5
        with:
          name: "freaklog-unsigned.apk"

      - name: Setup Android SDK
        if: >
          github.event_name == 'push'
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;35.0.0"

      - name: Sign app APK
        uses: ilharp/sign-android-release@nightly
        id: sign
        if: >
          github.event_name == 'push'
        with:
          releaseDir: .
          signingKey: ${{ secrets.KEYSTORE }}
          keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: Rename signed APK
        if: >
          github.event_name == 'push'
        run: |
          mv "${{ steps.sign.outputs.signedFile }}" "freaklog.apk"

      # Uploads to the action results if not pointed at a tag
      - uses: actions/upload-artifact@v4
        if: >
          github.event_name == 'push'
        with:
          name: "freaklog.apk"
          path: "freaklog.apk"
          if-no-files-found: error

      # Creates a release if pointed at a tag
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          files: "freaklog.apk"
          fail_on_unmatched_files: true
          make_latest: true

  upload_to_s3:
    needs: [ sign, build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download APKs
        uses: actions/download-artifact@v5
        with:
          path: apks

      - name: Upload APKs to S3
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: apks
          destination-dir: apks
          keep-file-fresh: true

