---
name: Build and sign aab
# only run on main branch to avoid running untrusted code on the self hosted runner
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: build aab
        run: ./gradlew bundle --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

  sign:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download unsigned app bundle
        uses: actions/download-artifact@v5
        with:
          name: app-release.aab

      - name: Setup Android SDK
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;35.0.0"

      - name: Sign aab
        uses: ilharp/sign-android-release@nightly
        id: sign
        with:
          releaseDir: .
          signingKey: ${{ secrets.KEYSTORE }}
          keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: Rename signed AAB
        run: |
          mv "${{ steps.sign.outputs.signedFile }}" "freaklog.aab"

      # Uploads to the action results if not pointed at a tag
      - uses: actions/upload-artifact@v4
        with:
          name: "freaklog.aab"
          path: "freaklog.aab"
          if-no-files-found: error


  upload:
    needs: [ sign, build ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download AAB
        uses: actions/download-artifact@v5
        with:
          path: aabs

      - name: Upload AAB to S3
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: aabs
          destination-dir: aabs
          keep-file-fresh: true

      - name: upload to google play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: foo.pilz.freaklog
          releaseFiles: aabs/freaklog.aab/freaklog.aab
          track: internal