---
name: Build
on:
  push:
env:
  main_project_module: 'app'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: build app
        run: ./gradlew assembleRelease --no-daemon

      - name: Setup Android SDK
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;35.0.0"

      - name: Sign app APK
        uses: ilharp/sign-android-release@nightly
        id: sign
        with:
          signingKey: ${{ secrets.KEYSTORE }}
          keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: Rename signed APK
        run: |
          mv "${{steps.sign.outputs.signedFile}}" "psychonautwiki-journal.apk"

      # Uploads to the action results if not pointed at a tag
      - uses: actions/upload-artifact@v4
        with:
          name: "psychonautwiki-journal.apk"
          path: "psychonautwiki-journal.apk"
          if-no-files-found: error

      # Creates a release if pointed at a tag
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: "psychonautwiki-journal.apk"
          fail_on_unmatched_files: true
          make_latest: true
