---
name: Build and sign APK
on:
  push:
  pull_request:
env:
  main_project_module: 'app'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable


    - name: build aab
      run: nix build .#aab

    - name: build apk
      run: nix build .#app

    - uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: result/bin/*
        if-no-files-found: error
  sign:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download unsigned builds
        if: >
          github.event_name == 'push'
        uses: actions/download-artifact@v5

      - name: Setup Android SDK
        if: >
          github.event_name == 'push'
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;35.0.0"

      - name: Sign app
        uses: ilharp/sign-android-release@nightly
        id: sign_app
        if: >
          github.event_name == 'push'
        with:
          releaseDir: build-outputs
          signingKey: ${{ secrets.KEYSTORE }}
          keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: split signed files
        uses: jungwinter/split@v2
        id: signed_files
        with:
          msg: ${{ steps.sign_app.outputs.signedFiles }}
          separator: ':'

      - uses: actions/upload-artifact@v4
        if: >
          github.event_name == 'push'
        with:
          name: "freaklog"
          path: |
            ${{ steps.signed_files.outputs._0 }}
            ${{ steps.signed_files.outputs._1 }}
            ${{ steps.signed_files.outputs._2 }}

      # Creates a release if pointed at a tag
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          files: "freaklog"
          make_latest: true

  upload:
    needs: [ sign, build ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download APKs
        uses: actions/download-artifact@v5
        with:
          path: .

      - name: Upload APKs to S3
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: freaklog
          destination-dir: apks
          keep-file-fresh: true

      - name: upload to google play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: foo.pilz.freaklog
          releaseFiles: apks/freaklog/app-release.aab
          track: internal